#!/usr/bin/env node
// Regenerates src/rdap-bootstrap.ts from the IANA RDAP bootstrap registry.
// Usage: npm run update-rdap

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const OUT = fileURLToPath(new URL("../src/rdap-bootstrap.ts", import.meta.url));
const BASE = "https://data.iana.org/rdap";

async function fetchRegistry(name) {
  const resp = await fetch(`${BASE}/${name}.json`);
  if (!resp.ok) throw new Error(`HTTP ${resp.status} fetching ${name}.json`);
  const data = await resp.json();
  if (!Array.isArray(data.services)) throw new Error(`${name}.json: missing services array`);
  return data;
}

// Returns [identifier, url] pairs, preferring an HTTPS URL for each service.
function entries(registry) {
  const out = [];
  for (const [ids, urls] of registry.services) {
    if (!ids?.length || !urls?.length) continue;
    const url = urls.find((u) => u.startsWith("https://")) ?? urls[0];
    for (const id of ids) out.push([id.toLowerCase(), url]);
  }
  return out;
}

const q = JSON.stringify;

const [dns, ipv4, ipv6, asn] = await Promise.all(
  ["dns", "ipv4", "ipv6", "asn"].map(fetchRegistry)
);

const dnsEntries = entries(dns).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
const ipEntries = [...entries(ipv4), ...entries(ipv6)];
const asnEntries = entries(asn)
  .map(([range, url]) => {
    const [lo, hi = lo] = range.split("-").map(Number);
    if (!Number.isInteger(lo) || !Number.isInteger(hi)) throw new Error(`bad ASN range: ${range}`);
    return [lo, hi, url];
  })
  .sort((a, b) => a[0] - b[0]);

if (dnsEntries.length < 1000 || ipEntries.length < 100 || asnEntries.length < 50) {
  throw new Error(
    `suspiciously small registry (dns=${dnsEntries.length} ip=${ipEntries.length} asn=${asnEntries.length}); refusing to write`
  );
}

const src = `// Generated by scripts/update-rdap.mjs from ${BASE}/ — do not edit by hand.
// Publication dates: dns ${dns.publication}, ipv4 ${ipv4.publication}, ipv6 ${ipv6.publication}, asn ${asn.publication}

// TLD → RDAP base URL
export const RDAP_DNS: Record<string, string> = {
${dnsEntries.map(([k, v]) => `\t${q(k)}: ${q(v)},`).join("\n")}
};

// [CIDR, RDAP base URL] (IPv4 and IPv6)
export const RDAP_IP: [string, string][] = [
${ipEntries.map(([k, v]) => `\t[${q(k)}, ${q(v)}],`).join("\n")}
];

// [first ASN, last ASN, RDAP base URL]
export const RDAP_ASN: [number, number, string][] = [
${asnEntries.map(([lo, hi, v]) => `\t[${lo}, ${hi}, ${q(v)}],`).join("\n")}
];
`;

await writeFile(OUT, src);
console.log(
  `wrote ${OUT}: ${dnsEntries.length} TLDs, ${ipEntries.length} IP blocks, ${asnEntries.length} ASN ranges`
);
